# Generated by Django 5.0.2 on 2024-03-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
