# Generated by Django 5.0.2 on 2024-03-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_contenido_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fechaCreada',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=models.TextField(default='Sin Comentario.', max_length=1000, null=True),
        ),
    ]
