# Generated by Django 5.0.2 on 2024-03-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contenido_fechacreada_alter_contenido_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='fechaCreada',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
